### ISSUE TITLE
Win Prediction of each round

### ISSUE THREAD

**Issue by LeonardoFBR** [Gonzih/tft-meta-analysis#1]
Is there any way to know the result of a fight knowing the champions and rivals?

**Comment by Gonzih** [comment]
No, not really. Riot API only exports final results of a game, so there is no public data available on early game comp win rates, mid game etc etc. But that would be cool though.

**Comment by Gonzih** [comment]
[Here](https://spontaneous-stroopwafel-0c311e.netlify.app/meta.html)  is winrate analysis, but that is only for challenger and GM ladders.

**Comment by LeonardoFBR** [comment]
https://www.reddit.com/r/TeamfightTactics/comments/pwd7km/i_made_an_ai_to_predict_the_outcome_of_a_pvp_round/?utm_medium=android_app&utm_source=share

**Comment by LeonardoFBR** [comment]
This is an example

**Comment by LeonardoFBR** [comment]
There he says as he did in his comments.

**Comment by LeonardoFBR** [comment]
https://www.reddit.com/r/TeamfightTactics/comments/q6xr2n/sneak_peek_at_my_tft_rl_environment/?utm_medium=android_app&utm_source=share

**Comment by Gonzih** [comment]
Yeah, its possible, but not really necessary.

Data from riot API is about end state of a game, not outcome of a round, so this model is estimation. 
And sometimes estimations are correct, sometimes not.

Its possible to train a model, find example of model outcome and then clip that confirms models output.
Does not make model correct though.
Correlation isn't causation.

Its possible to achieve similar result with much simpler statistical approaches, I just don't see point in doing so.

**Comment by Gonzih** [comment]
What would be interesting is to have ability to run ML that picks up comps and tests them against other comps (either from data or also ML generated), that would give good insight in meta comps that are unknown to the community. Unfortunately that requires access to client internal to run simulations.

**Comment by LeonardoFBR** [comment]
https://github.com/tacticians-academy/teamfight-simulator

This one can simulate matches, but it is outdated

**Comment by Gonzih** [comment]
Yeah, its more like emulator, interesting that its frontend only.
If you wanna run your own analysis you can get data from docker image
Just clone this repo and run `make docker-pull-public docker-cp-from-public` and it should populate `notebooks/data` folder with all data in CSV files.

Data is currently only for GM/Challenger leagues, cant scrape master anymore, takes longer than 6 hours.
